-- MySQL Script generated by MySQL Workbench
-- Mon Oct 26 19:00:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_id` INT NOT NULL,
  `a_surname` VARCHAR(50) NOT NULL,
  `a_name` VARCHAR(50) NOT NULL,
  `a_patronymic` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `ISBN` INT NOT NULL,
  `book_name` VARCHAR(50) NOT NULL,
  `year_pub` INT NOT NULL,
  `num_pages` INT NOT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books_has_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_has_author` (
  `books_ISBN` INT NOT NULL,
  `author_author_id` INT NOT NULL,
  PRIMARY KEY (`books_ISBN`, `author_author_id`),
  INDEX `fk_books_has_author_author1_idx` (`author_author_id` ASC) VISIBLE,
  INDEX `fk_books_has_author_books1_idx` (`books_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_books_has_author_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_author_author1`
    FOREIGN KEY (`author_author_id`)
    REFERENCES `mydb`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books_has_sys_directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_has_sys_directory` (
  `books_ISBN` INT NOT NULL,
  `sys_directory_know_code` INT NOT NULL,
  PRIMARY KEY (`books_ISBN`, `sys_directory_know_code`),
  INDEX `fk_books_has_sys_directory_sys_directory1_idx` (`sys_directory_know_code` ASC) VISIBLE,
  INDEX `fk_books_has_sys_directory_books1_idx` (`books_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_books_has_sys_directory_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_sys_directory_sys_directory1`
    FOREIGN KEY (`sys_directory_know_code`)
    REFERENCES `mydb`.`sys_directory` (`know_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instance` (
  `inventory_id` INT NOT NULL,
  `presence` VARCHAR(3) NOT NULL,
  `capture_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `reader_libcard_id` INT NOT NULL,
  `books_ISBN` INT NOT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_instance_reader1_idx` (`reader_libcard_id` ASC) VISIBLE,
  INDEX `fk_instance_books1_idx` (`books_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_instance_reader1`
    FOREIGN KEY (`reader_libcard_id`)
    REFERENCES `mydb`.`reader` (`libcard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instance_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reader` (
  `libcard_id` INT NOT NULL,
  `FIO` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `phone_home` VARCHAR(12) NULL,
  `phone_work` VARCHAR(12) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`libcard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_directory` (
  `know_code` INT NOT NULL,
  `know_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`know_code`))
ENGINE = InnoDB;

CREATE USER 'Student' IDENTIFIED BY 'student';

GRANT SELECT ON TABLE `mydb`.* TO 'Student';
CREATE USER 'Prepod' IDENTIFIED BY 'prepod';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'Prepod';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
