-- MySQL Script generated by MySQL Workbench
-- Mon Oct 26 19:03:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `group_id` INT NOT NULL,
  `group_name` VARCHAR(100) NULL,
  `curator` VARCHAR(100) NULL,
  `group_number` VARCHAR(100) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_id` INT NOT NULL,
  `student_full_name` VARCHAR(100) NULL,
  `student_number` DECIMAL(17) NULL,
  `student_adress` VARCHAR(100) NULL,
  `groups_group_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_Student_groups1`
    FOREIGN KEY (`groups_group_id`)
    REFERENCES `mydb`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Student_groups1_idx` ON `mydb`.`Student` (`groups_group_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faculties` (
  `faculty_cabinet_id` INT NOT NULL,
  `facuty_big_boss` VARCHAR(100) NULL,
  `faculty_prepod` VARCHAR(100) NULL,
  PRIMARY KEY (`faculty_cabinet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prepodavateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prepodavateli` (
  `prepod_id` INT NOT NULL,
  `prepod_full_name` VARCHAR(100) NULL,
  `faculties_faculty_cabinet_id` INT NOT NULL,
  PRIMARY KEY (`prepod_id`),
  CONSTRAINT `fk_prepodavateli_faculties1`
    FOREIGN KEY (`faculties_faculty_cabinet_id`)
    REFERENCES `mydb`.`faculties` (`faculty_cabinet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prepodavateli_faculties1_idx` ON `mydb`.`prepodavateli` (`faculties_faculty_cabinet_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Predmeti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predmeti` (
  `predmet_id` INT NOT NULL,
  `predmet_name` VARCHAR(100) NULL,
  `Student_student_id` INT NOT NULL,
  `Student_gruppi_group_id` INT NOT NULL,
  `Prepodavateli_prepod_id` INT NOT NULL,
  PRIMARY KEY (`predmet_id`, `Student_student_id`, `Student_gruppi_group_id`, `Prepodavateli_prepod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book po predmetam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book po predmetam` (
  `book_id` INT NOT NULL,
  `book_name` VARCHAR(100) NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predmeti_has_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predmeti_has_Student` (
  `Predmeti_predmet_id` INT NOT NULL,
  `Predmeti_Student_student_id` INT NOT NULL,
  `Predmeti_Student_gruppi_group_id` INT NOT NULL,
  `Predmeti_Prepodavateli_prepod_id` INT NOT NULL,
  `Student_student_id` INT NOT NULL,
  PRIMARY KEY (`Predmeti_predmet_id`, `Predmeti_Student_student_id`, `Predmeti_Student_gruppi_group_id`, `Predmeti_Prepodavateli_prepod_id`, `Student_student_id`),
  CONSTRAINT `fk_Predmeti_has_Student_Predmeti1`
    FOREIGN KEY (`Predmeti_predmet_id` , `Predmeti_Student_student_id` , `Predmeti_Student_gruppi_group_id` , `Predmeti_Prepodavateli_prepod_id`)
    REFERENCES `mydb`.`Predmeti` (`predmet_id` , `Student_student_id` , `Student_gruppi_group_id` , `Prepodavateli_prepod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Predmeti_has_Student_Student1`
    FOREIGN KEY (`Student_student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Predmeti_has_Student_Student1_idx` ON `mydb`.`Predmeti_has_Student` (`Student_student_id` ASC) VISIBLE;

CREATE INDEX `fk_Predmeti_has_Student_Predmeti1_idx` ON `mydb`.`Predmeti_has_Student` (`Predmeti_predmet_id` ASC, `Predmeti_Student_student_id` ASC, `Predmeti_Student_gruppi_group_id` ASC, `Predmeti_Prepodavateli_prepod_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`prepodavateli_has_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prepodavateli_has_Student` (
  `prepodavateli_prepod_id` INT NOT NULL,
  `Student_student_id` INT NOT NULL,
  PRIMARY KEY (`prepodavateli_prepod_id`, `Student_student_id`),
  CONSTRAINT `fk_prepodavateli_has_Student_prepodavateli1`
    FOREIGN KEY (`prepodavateli_prepod_id`)
    REFERENCES `mydb`.`prepodavateli` (`prepod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prepodavateli_has_Student_Student1`
    FOREIGN KEY (`Student_student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prepodavateli_has_Student_Student1_idx` ON `mydb`.`prepodavateli_has_Student` (`Student_student_id` ASC) VISIBLE;

CREATE INDEX `fk_prepodavateli_has_Student_prepodavateli1_idx` ON `mydb`.`prepodavateli_has_Student` (`prepodavateli_prepod_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Predmeti_has_Book po predmetam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predmeti_has_Book po predmetam` (
  `Predmeti_predmet_id` INT NOT NULL,
  `Predmeti_Student_student_id` INT NOT NULL,
  `Predmeti_Student_gruppi_group_id` INT NOT NULL,
  `Predmeti_Prepodavateli_prepod_id` INT NOT NULL,
  `Book po predmetam_book_id` INT NOT NULL,
  PRIMARY KEY (`Predmeti_predmet_id`, `Predmeti_Student_student_id`, `Predmeti_Student_gruppi_group_id`, `Predmeti_Prepodavateli_prepod_id`, `Book po predmetam_book_id`),
  CONSTRAINT `fk_Predmeti_has_Book po predmetam_Predmeti1`
    FOREIGN KEY (`Predmeti_predmet_id` , `Predmeti_Student_student_id` , `Predmeti_Student_gruppi_group_id` , `Predmeti_Prepodavateli_prepod_id`)
    REFERENCES `mydb`.`Predmeti` (`predmet_id` , `Student_student_id` , `Student_gruppi_group_id` , `Prepodavateli_prepod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Predmeti_has_Book po predmetam_Book po predmetam1`
    FOREIGN KEY (`Book po predmetam_book_id`)
    REFERENCES `mydb`.`Book po predmetam` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Predmeti_has_Book po predmetam_Book po predmetam1_idx` ON `mydb`.`Predmeti_has_Book po predmetam` (`Book po predmetam_book_id` ASC) VISIBLE;

CREATE INDEX `fk_Predmeti_has_Book po predmetam_Predmeti1_idx` ON `mydb`.`Predmeti_has_Book po predmetam` (`Predmeti_predmet_id` ASC, `Predmeti_Student_student_id` ASC, `Predmeti_Student_gruppi_group_id` ASC, `Predmeti_Prepodavateli_prepod_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `ISBN` INT NOT NULL,
  `book_name` VARCHAR(50) NOT NULL,
  `year_pub` INT NOT NULL,
  `num_pages` INT NOT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_id` INT NOT NULL,
  `a_surname` VARCHAR(50) NOT NULL,
  `a_name` VARCHAR(50) NOT NULL,
  `a_patronymic` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reader` (
  `libcard_id` INT NOT NULL,
  `FIO` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `phone_home` VARCHAR(12) NULL,
  `phone_work` VARCHAR(12) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`libcard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_directory` (
  `know_code` INT NOT NULL,
  `know_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`know_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instance` (
  `inventory_id` INT NOT NULL,
  `presence` VARCHAR(3) NOT NULL,
  `capture_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `reader_libcard_id` INT NOT NULL,
  `books_ISBN` INT NOT NULL,
  PRIMARY KEY (`inventory_id`),
  CONSTRAINT `fk_instance_reader1`
    FOREIGN KEY (`reader_libcard_id`)
    REFERENCES `mydb`.`reader` (`libcard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instance_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_instance_reader1_idx` ON `mydb`.`instance` (`reader_libcard_id` ASC) VISIBLE;

CREATE INDEX `fk_instance_books1_idx` ON `mydb`.`instance` (`books_ISBN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`books_has_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_has_author` (
  `books_ISBN` INT NOT NULL,
  `author_author_id` INT NOT NULL,
  PRIMARY KEY (`books_ISBN`, `author_author_id`),
  CONSTRAINT `fk_books_has_author_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_author_author1`
    FOREIGN KEY (`author_author_id`)
    REFERENCES `mydb`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_books_has_author_author1_idx` ON `mydb`.`books_has_author` (`author_author_id` ASC) VISIBLE;

CREATE INDEX `fk_books_has_author_books1_idx` ON `mydb`.`books_has_author` (`books_ISBN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`books_has_sys_directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_has_sys_directory` (
  `books_ISBN` INT NOT NULL,
  `sys_directory_know_code` INT NOT NULL,
  PRIMARY KEY (`books_ISBN`, `sys_directory_know_code`),
  CONSTRAINT `fk_books_has_sys_directory_books1`
    FOREIGN KEY (`books_ISBN`)
    REFERENCES `mydb`.`books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_sys_directory_sys_directory1`
    FOREIGN KEY (`sys_directory_know_code`)
    REFERENCES `mydb`.`sys_directory` (`know_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_books_has_sys_directory_sys_directory1_idx` ON `mydb`.`books_has_sys_directory` (`sys_directory_know_code` ASC) VISIBLE;

CREATE INDEX `fk_books_has_sys_directory_books1_idx` ON `mydb`.`books_has_sys_directory` (`books_ISBN` ASC) VISIBLE;

CREATE USER 'Student' IDENTIFIED BY 'student';

GRANT SELECT ON TABLE `mydb`.* TO 'Student';
CREATE USER 'Prepod' IDENTIFIED BY 'prepod';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'Prepod';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
